---
# WAN Pathfinder nodes variables

wan_rr:
  defaults:
    platform: CloudEOS
    data_plane_cpu_allocation_max: 1 # (1)!
    loopback_ipv4_pool: 192.168.255.0/24
    vtep_loopback_ipv4_pool: 192.168.42.0/24
    bgp_as: 65000
  nodes:
    - name: pf1
      id: 1
      mgmt_ip: 192.168.17.10/24
      cv_pathfinder_site: PF1-GLOBAL # (2)!
      # WAN interfaces
      l3_interfaces:
        - name: Ethernet1
          peer: mpls-cloud
          peer_interface: Ethernet1
          peer_ip: 172.18.100.1
          ip_address: 172.18.100.2/24
          wan_carrier: ACME-MPLS-INC
          wan_circuit_id: mpls-pf1
          # The static_routes uses the peer_ip as next-hop
          static_routes:
            - prefix: 172.18.0.0/16
        - name: Ethernet2
          peer: inet-cloud
          peer_interface: Ethernet1
          peer_ip: 100.64.100.1
          ip_address: 100.64.100.2/24
          wan_carrier: GLOBAL-INTERNET-LIMITED
          wan_circuit_id: inet-pf1
          ipv4_acl_in: ACL-PF-INTERNET-IN
          static_routes:
            - prefix: 0.0.0.0/0
    - name: pf2
      id: 2
      mgmt_ip: 192.168.17.11/24
      cv_pathfinder_site: PF2-GLOBAL
      # WAN interfaces
      l3_interfaces:
        - name: Ethernet1
          peer: mpls-cloud
          peer_interface: Ethernet2
          peer_ip: 172.18.200.1
          ip_address: 172.18.200.2/24
          wan_carrier: ACME-MPLS-INC
          wan_circuit_id: mpls-pf2
          # The static_routes uses the peer_ip as next-hop
          static_routes:
            - prefix: 172.18.0.0/16
        - name: Ethernet2
          peer: inet-cloud
          peer_interface: Ethernet2
          peer_ip: 100.64.200.1
          ip_address: 100.64.200.2/24
          wan_carrier: GLOBAL-INTERNET-LIMITED
          wan_circuit_id: inet-pf2
          ipv4_acl_in: ACL-PF-INTERNET-IN
          static_routes:
            - prefix: 0.0.0.0/0
