---
type: l3leaf

# L3 Leaf switch group
l3leaf:
  defaults:
    # Set the relevant platform as each platform has different default values in Ansible AVD
    platform: vEOS-lab
    # Logical Pool of Router ID's, formatted as IPv4 addresses, to configure BGP router ID. Does not configure any IPv4 address
    router_id_pool: 10.255.1.0/24
    # Pool of IPv6 addresses to configure interface Loopback0 used for BGP EVPN sessions
    loopback_ipv6_pool: 2001:DB8:1::/48
    # Pool of IPv6 addresses to be used as Virtual Tunnel EndPoint (VXLAN origin and destination IPs)
    vtep_loopback_ipv6_pool: 2001:DB8:5::/48
    # Ansible hostname of the devices used to establish neighborship (IP assignments and BGP peering)
    uplink_switches: ['dc1-spine1', 'dc1-spine2']
    # Pool of IPv6 addresses to be used in P2P links
    uplink_ipv6_pool: 2001:DB8:2::/48
    # descitpion
    mlag_peer_address_family: ipv6
    # Pool of IPv6 addresses to be used for MLAG peer-link connectivity
    mlag_peer_ipv6_pool: 2001:DB8:3::/48
    # iBGP Peering between MLAG peers
    mlag_peer_l3_ipv6_pool: 2001:DB8:4::/48
    # Virtual router mac for VNIs assigned to Leaf switches in format xx:xx:xx:xx:xx:xx
    virtual_router_mac_address: 00:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp

# If two nodes (and only two) are in the same node_group, they will automatically form an MLAG pair
  node_groups:
    # Definition of a node group that will include two devices in MLAG.
    # Definitions under the group will be inherited by both nodes in the group
    - group: DC1_L3_LEAF1
      # ASN to be used by BGP for the group. Both devices in the MLAG pair will use the same BGP ASN
      bgp_as: 65101
      nodes:
        # Definition of hostnames under the node_group
        - name: dc1-leaf1a
          id: 1
          mgmt_ip: 172.16.1.101/24
          # Definition of the port to be used in the uplink device facing this device.
          # Note that the number of elements in this list must match the length of 'uplink_switches' as well as 'uplink_interfaces'
          uplink_switch_interfaces: [Ethernet1, Ethernet1]
        - name: dc1-leaf1b
          id: 2
          mgmt_ip: 172.16.1.102/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2]
    - group: DC1_L3_LEAF2
      bgp_as: 65102
      nodes:
        - name: dc1-leaf2a
          id: 3
          mgmt_ip: 172.16.1.103/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3]
        - name: dc1-leaf2b
          id: 4
          mgmt_ip: 172.16.1.104/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4]
