---
### group_vars/DC1.yml

# local users
local_users:
  # Username with no password configured
  - name: admin
    privilege: 15
    role: network-admin
    no_password: true

  # Username with a password
  - name: arista
    privilege: 15
    role: network-admin
    sha512_password: "$6$Enl0WfE32FthwyiJ$yTyGaEJ2uPKLU.F7314YtB7J1jrzrMi7ogXIRTEHQfLdLgKWWmr1UvNlZLN6AyuxET7G5aH3AI9OYRzxVTkB1."

# AAA Authorization
custom_structured_configuration_aaa_authorization:
  exec:
    default: local

# OOB Management network default gateway.
mgmt_gateway: 172.16.100.1
mgmt_interface: Management0

# dns servers.
dns_settings:
  servers:
    - ip_address: 8.8.4.4
    - ip_address: 8.8.8.8

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp_settings:
  server_vrf: use_mgmt_interface_vrf
  servers:
    - name: time.google.com
    - name: pool.ntp.org
